spring:
  mail:
    host: smtp.gmail.com
    username: ${EMAIL}
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    password: ${EMAIL_CODE}

  application:
    name: kiwi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect